Table "dbo"."dim_date" as DD {
  "date" date [pk]
  "date_int" int
  "year" tinyint
  "calendar_month" varchar
  "month" tinyint
  "calendar_day" varchar
  "day_of_week" tinyint
  "day_of_week_start_monday" tinyint
  "is_week_day" tinyint
  "day_of_month" tinyint
  "is_last_day_of_month" bool
  "day_of_year" tinyint
  "week_of_year_iso" tinyint
  "quarter_of_year" tinyint
}

Table "dbo"."dim_riders" as DR {
  "rider_id" bigint [pk, not null]
  "first" varchar
  "last" varchar
  "address" varchar
  "birthday" timestamp
  "account_start_date" timestamp
  "account_end_date" timestamp
  "is_member" bit
}

Table "dbo"."dim_stations" as DS {
  "station_id" varchar [pk, not null]
  "name" varchar
  "latitude" float
  "longitude" float
}

Table "dbo"."fact_trips" as FT {
  "trip_id" varchar [pk]
  "time_spent" int
  "rideable_type" varchar
  "rider_age_at_time" int
  "rider_id" bigint
  "start_station_id" varchar
  "start_at" timestamp
  "start_at_date" date
  "end_station_id" varchar
  "ended_at" timestamp
  "ended_at_date" date
  "is_member" bit
}

Table "divvy"."fact_payments" as FP {
  "payment_id" bigint [pk]
  "amount" decimal(14,2)
  "date" date
  "rider_id" bigint
  "rider_age_account_start" int
}

Ref: FT.start_at_date > DD.date
Ref: FT.ended_at_date > DD.date
Ref: FT.rider_id > DR.rider_id
Ref: FT.start_station_id > DS.station_id
Ref: FT.end_station_id > DS.station_id
Ref: FP.date > DD.date
Ref: FP.rider_id > DR.rider_id